export const PROGRESS_THRESHOLDS = {
  trendFlatPercent: 2,
  minimumTrendSessions: 4,
  minimumTrendSpanDays: 14,
  noNewBestSessions: 4,
  noNewBestDays: 21,
  mainLiftMinimumSessions: 3,
  mostImprovedMinimumSessions: 4,
  pushPullMinimumSets: 20,
  pushPullRatio: 2,
  rirMinimumCoverage: 0.3,
  rirChangeThreshold: 1,
  commonRangeMinimumSets: 10,
  commonRangeMaximumSets: 20,
  deloadWeek: 6,
  legacyDeloadBlockNumber: 8,
  legacyDeloadWeek: 1,
  recentRecordDays: 7,
} as const
