"""Builds the v2 catalogue seed SQL from the approved JSON files.

Source of truth: docs/fitness/approved/catalogue-v2/*.json (validated with
scripts/validate-catalogue.py). Output: SQL upsert on stdout.
"""
import json
import sys
from pathlib import Path

SOURCE = Path('docs/fitness/approved/catalogue-v2')


def text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def array(values) -> str:
    return 'array[' + ', '.join(text(v) for v in values) + ']::text[]' if values else "'{}'::text[]"


def main():
    exercises = []
    for file in sorted(SOURCE.glob('*.json')):
        exercises += json.loads(file.read_text(encoding='utf-8'))
    if not exercises:
        sys.exit(f'no exercises found in {SOURCE}')
    exercises.sort(key=lambda e: e['id'])

    print(f'-- Generated by scripts/catalogue-v2-seed.py from {SOURCE}/*.json')
    print(f'-- {len(exercises)} exercises. Re-run the script instead of editing by hand.')
    print('insert into public.exercises (id, name_en, name_es, body_region, primary_muscle, primary_muscles,')
    print('  secondary_muscles, equipment, movement_pattern, mechanic, laterality, posture_tips, squeeze_cue, aliases, is_active) values')
    rows = [
        '  (' + ', '.join([
            text(e['id']), text(e['name_en']), text(e['name_es']), text(e['body_region']),
            text(e['primary_muscles'][0]), array(e['primary_muscles']), array(e['secondary_muscles']),
            text(e['equipment']), text(e['movement_pattern']), text(e['mechanic']), text(e['laterality']),
            array(e['posture_tips']), text(e['squeeze_cue']), array(e['aliases']), 'true',
        ]) + ')'
        for e in exercises
    ]
    print(',\n'.join(rows))
    print('on conflict (id) do update set')
    columns = ['name_en', 'name_es', 'body_region', 'primary_muscle', 'primary_muscles', 'secondary_muscles',
               'equipment', 'movement_pattern', 'mechanic', 'laterality', 'posture_tips', 'squeeze_cue', 'aliases', 'is_active']
    print(',\n'.join(f'  {c} = excluded.{c}' for c in columns) + ',\n  updated_at = now();')


if __name__ == '__main__':
    main()
