"""Builds the exercise catalogue seed from the approved fitness document.

Source of truth: docs/fitness/approved/2026-10-03-exercise-catalogue.md
Output: SQL upsert statements on stdout.
"""
import re
import sys

DOC = 'docs/fitness/approved/2026-10-03-exercise-catalogue.md'


def clean(cell: str) -> str:
    cell = cell.replace('**NEW**', '')
    cell = re.sub(r'⚠️\s*REVISAR(\s*\([^)]*\))?', '', cell)
    cell = re.sub(r'\(posible fusión[^)]*\)', '', cell)
    return cell.strip().strip('—').strip()


def parse(text: str):
    section = text.split('## Catálogo propuesto', 1)[1].split('\n## ', 1)[0]
    rows = []
    for line in section.splitlines():
        if not line.startswith('| `'):
            continue
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        exercise_id = re.search(r'`([a-z0-9-]+)`', cells[0]).group(1)
        secondary = [m.strip() for m in clean(cells[4]).split(',') if m.strip()]
        aliases = re.findall(r'`([a-z0-9-]+)`', cells[7])
        rows.append({
            'id': exercise_id,
            'name_en': clean(cells[1]),
            'name_es': clean(cells[2]),
            'primary_muscle': clean(cells[3]),
            'secondary_muscles': secondary,
            'equipment': clean(cells[5]),
            'movement_pattern': clean(cells[6]),
            'aliases': aliases,
        })
    return rows


def sql_text(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_array(values) -> str:
    return "array[" + ', '.join(sql_text(v) for v in values) + "]::text[]" if values else "'{}'::text[]"


def main():
    rows = parse(open(DOC, encoding='utf-8').read())
    ids = [r['id'] for r in rows]
    if len(set(ids)) != len(ids):
        sys.exit('duplicate ids in approved catalogue')
    print(f'-- Generated by scripts/catalogue-from-approved.py from {DOC}')
    print(f'-- {len(rows)} exercises. Re-run the script instead of editing by hand.')
    print('insert into public.exercises (id, name_en, name_es, primary_muscle, secondary_muscles, equipment, movement_pattern, aliases) values')
    values = [
        f"  ({sql_text(r['id'])}, {sql_text(r['name_en'])}, {sql_text(r['name_es'])}, {sql_text(r['primary_muscle'])}, "
        f"{sql_array(r['secondary_muscles'])}, {sql_text(r['equipment'])}, {sql_text(r['movement_pattern'])}, {sql_array(r['aliases'])})"
        for r in rows
    ]
    print(',\n'.join(values))
    print('on conflict (id) do update set name_en = excluded.name_en, name_es = excluded.name_es,')
    print('  primary_muscle = excluded.primary_muscle, secondary_muscles = excluded.secondary_muscles,')
    print('  equipment = excluded.equipment, movement_pattern = excluded.movement_pattern,')
    print('  aliases = excluded.aliases, updated_at = now();')


if __name__ == '__main__':
    main()
