"""Builds training-block seed SQL from the approved JSON.

Source of truth: docs/fitness/approved/training-blocks/ (blocks.json and
catalogue-additions.json), validated with scripts/validate-blocks.py.
Output: SQL upserts on stdout (catalogue additions first, then blocks).
"""
import json
from pathlib import Path

SOURCE = Path('docs/fitness/approved/training-blocks')


def text(value) -> str:
    if value is None:
        return 'null'
    return "'" + str(value).replace("'", "''") + "'"


def array(values) -> str:
    return 'array[' + ', '.join(text(v) for v in values) + ']::text[]' if values else "'{}'::text[]"


def main():
    blocks = json.loads((SOURCE / 'blocks.json').read_text(encoding='utf-8'))
    additions_file = SOURCE / 'catalogue-additions.json'
    additions = json.loads(additions_file.read_text(encoding='utf-8')) if additions_file.exists() else []

    print(f'-- Generated by scripts/training-blocks-seed.py from {SOURCE}')
    print(f'-- {len(blocks)} blocks, {len(additions)} catalogue additions. Re-run instead of editing by hand.')

    for e in additions:
        print('insert into public.exercises (id, name_en, name_es, body_region, primary_muscle, primary_muscles, '
              'secondary_muscles, equipment, movement_pattern, mechanic, laterality, posture_tips, aliases) values ('
              + ', '.join([
                  text(e['id']), text(e['name_en']), text(e.get('name_es', e['name_en'])), text(e['body_region']),
                  text(e['primary_muscles'][0]), array(e['primary_muscles']), array(e['secondary_muscles']),
                  text(e['equipment']), text(e['movement_pattern']), text(e['mechanic']), text(e['laterality']),
                  array(e['posture_tips']), array(e['aliases']),
              ]) + ') on conflict (id) do nothing;')

    for b in blocks:
        print(f"\ninsert into public.training_blocks (id, number, name, method, start_date, weeks, origin, summary) values ("
              f"{text(b['id'])}, {b['number']}, {text(b['name'])}, {text(b['method'])}, {text(b['start_date'])}, "
              f"{b['weeks']}, {text(b['origin'])}, {text(b['summary'])}) on conflict (id) do update set "
              "number = excluded.number, name = excluded.name, method = excluded.method, start_date = excluded.start_date, "
              "weeks = excluded.weeks, origin = excluded.origin, summary = excluded.summary, updated_at = now();")
        for position, day in enumerate(b['days'], 1):
            print(f"insert into public.training_block_days (block_id, key, position, name, focus) values ("
                  f"{text(b['id'])}, {text(day['key'])}, {position}, {text(day['name'])}, {text(day.get('focus'))}) "
                  "on conflict (block_id, key) do update set position = excluded.position, name = excluded.name, "
                  "focus = excluded.focus;")
            for ex_position, ex in enumerate(day['exercises'], 1):
                print(f"insert into public.training_block_exercises (block_id, day_key, code, position, exercise_id, sets, "
                      f"reps, rest_seconds, technique, angle_degrees, notes) values ("
                      f"{text(b['id'])}, {text(day['key'])}, {text(ex['code'])}, {ex_position}, {text(ex['exercise_id'])}, "
                      f"{ex['sets']}, {array(ex['reps'])}, {ex['rest_seconds']}, {text(ex['technique'])}, "
                      f"{ex['angle_degrees'] if ex.get('angle_degrees') is not None else 'null'}, {text(ex.get('notes') or None)}) "
                      "on conflict (block_id, day_key, code) do update set position = excluded.position, "
                      "exercise_id = excluded.exercise_id, sets = excluded.sets, reps = excluded.reps, "
                      "rest_seconds = excluded.rest_seconds, technique = excluded.technique, "
                      "angle_degrees = excluded.angle_degrees, notes = excluded.notes;")


if __name__ == '__main__':
    main()
